// Automatically generated file. Edit README.txt and run 
// 'make usage' to update this documentation!

char* usage_str = ""
"Usage: PROGNAME.exe <url>\n"
"\n"
"SYNOPSYS\n"
"\n"
"USAGE\n"
"\n"
"On many modern platforms it is possible to register custom protocol handlers \n"
"with the shell. This program is intended to map URIs to pre-confiured \n"
"programms and execute certain actions as well as limited input validation for\n"
"security reasons.\n"
"\n"
"Once the program is called, it expects a URI as first parameter or from stdin.\n"
"The URI is broken down into scheme, authority, path and query (see rfc3986,\n"
"section 3 for details). Once the described parts are extracted from the URI it \n"
"is mapped to a local executable. The definition which URIs can be mapped to \n"
"which executable is defined in PROGNAME.ini.\n"
"\n"
"Due to the non-interactive nature of such a program, a debug log can be written \n"
"to PROGNAME.log.\n"
"\n"
"This a quick overview how url parts are mapped to an executable command line \n"
"string:\n"
"\n"
"     foo://example/over/there?-a=1&-b=2#nose\n"
"     \\_/   \\______/\\________/ \\_______/ \\__/\n"
"      |        |         |           |    |__\n"
"   scheme  authority     path       query   fragment\n"
"      |     ___|______   ____|____    __|____    |_\n"
"     / \\   /          \\ /         \\  /       \\     |\n"
" [protocol] example.exe  [profile]    -a=1 -b=2    unused\n"
"\n"
"For this URI handler to work, it needs to be mapped to a protocol (foo in \n"
"the above example URI). This is done trough registering the protocol name to \n"
"the executable with your shell (in the registry for windows users).\n"
"\n"
"\n"
"CONFIGURATION\n"
"\n"
"You need to register this progam with you shell so that it recognizes your \n"
"protocol name (Scheme) and redirects calls to thei executable. On Windows this \n"
"is done trough the registry.\n"
"\n"
"An example registry file would look like this. Replace <proto> with your \n"
"protocol name (scheme) and <path> with an absolute path to your executable.\n"
"\n"
"===[REG FILE]===================================================================\n"
"Windows Registry Editor Version 5.00\n"
"\n"
"[HKEY_CLASSES_ROOT\\<proto>]\n"
"@=\"URL: <proto> Protocol\"\n"
"\"URL Protocol\"=\"\"\n"
"\n"
"[HKEY_CLASSES_ROOT\\<proto>\\shell]\n"
"[HKEY_CLASSES_ROOT\\<proto>\\shell\\open]\n"
"[HKEY_CLASSES_ROOT\\<proto>\\shell\\open\\command]\n"
"@=\"\\\"C:\\\\<path>\\\\protohand.exe\\\" \\\"%%1\\\"\"\n"
"===[EOF]========================================================================\n"
"\n"
"Mappings between URIs and executables are defined in PROGNAME.ini. There are 2 \n"
"actions that can be configured:\n"
"1. Run an executable that expects 1 command line argument which points to a \n"
"   document. This method can check if the document path is within a certain \n"
"   location (for security reasons).\n"
"\n"
"2. Executa a program with any number of command line arguments. This method \n"
"   is only as secure as the configuration allows. You need to take care\n"
"   that no arbitrary programs or code can be run.\n"
"\n"
"Esample ini file:\n"
"\n"
"===[INI FILE]===================================================================\n"
"[word/document]\n"
"default_path=\"\\\\server\\share\"\n"
";allowed_params=\n"
";path_params=\n"
"exe = word.exe\n"
"\n"
"[cmd/exe]\n"
"exe = cmd.exe\n"
"===[EOF]========================================================================\n"
"\n"
"exe:           TODO\n"
"allowed_path:  TODO\n"
"path_params:   TODO\n"
"default_path:  TODO\n"
"\n"
"\n"
"FILES\n"
"\n"
"	PROGNAME.exe - This executable\n"
"	PROGNAME.ini - Mapping between urls and executables. This file needs to \n"
"	               be located in the same folder as the executable.\n"
"	PROGNAME.log - (optional) enabled on compile time with the flag -DDEBUG=1\n"
"	               The log will be written into the same directory as the \n"
"	               executable. Make sure the program has write permission.\n"
"\n"
"\n"
"LIMITATIONS\n"
"1. The maximung length of an URI is limited to STDIN_MAX bytes \n"
"   (1024 by default).\n"
"\n"
"2. The maximung length of a command (with all it's parameters) is limited \n"
"   to MAX_CWD_LENGTH bytes (1024 by default).\n"
"\n"
"LICENSE\n"
"\n"
"This software is licensed by the BSD license. See LICENSE.txt in the source \n"
"code for the full license text.\n"
"\n"
"(c) 2017, Simon Wunderlin\n"
"\n"
"Please send pull requests to https://github.com/wunderlins/protohand.git, any\n"
"fix and etension is appreciated!\n"
"";
